### ISSUE TITLE
A bug encountered by me when reading projects.csv

### ISSUE THREAD

**Issue by mo666666** [mwcvitkovic/Supervised-Learning-on-Relational-Databases-with-GNNs#3]
Hi, mwcvitkovic! When I utilize your provided docker file and process the kddcup2014 dataset, I encounter a bug:
```
docker exec -i 625f51dcfb1a6772c34b20e3f77e297033e1d613dcac84c74be1cabe73550139 cypher-shell < /data/moyichuan/Relational_data/kddcup2014/kddcup2014_neo4j_loader.cypher


Couldn't load the external resource at: file:/data/projects.csv
```
Do you have any idea about the solution to this error?

**Comment by mwcvitkovic** [comment]
That file comes from the KDD cup dataset: https://www.kaggle.com/c/kdd-cup-2014-predicting-excitement-at-donors-choose/data

If you follow the instructions in README.md this error should go away

**Comment by mo666666** [comment]
Thank you for your replies! I will try to rerun the code!
